default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: <%=ENV['DB_HOST']%>

development:
  <<: *default
  database: <%=ENV['DB_DATABASE']%>
  user: <%=ENV['DB_USERNAME']%>
  password: <%=ENV['DB_PASSWORD']%>

test:
  <<: *default
  database: <%=ENV['DB_DATABASE_TEST']%>
  user: <%=ENV['DB_USERNAME_TEST']%>
  password: <%=ENV['DB_PASSWORD_TEST']%>
